### ISSUE TITLE
Rename config parameter: 'schema' to 'columns'

### ISSUE THREAD

**Issue by muga** [treasure-data/embulk-parser-query_string#21]
Since most of embulk plugins use 'columns' parameter representing column schema, let's change the name of 'schema' parameter with 'columns'.

**Comment by yoshihara** [comment]
@muga I fixed this issue by #22 and will release soon. Please wait a moment.

**Comment by yoshihara** [comment]
@muga I released embulk-parser-query_string 0.2.0. Thanks for your report!
