### ISSUE TITLE
Show skipped lines and the line numbers as log messages if the parser cannot parse lines and skip them

### ISSUE THREAD

**Issue by muga** [treasure-data/embulk-parser-query_string#28]
The current parser does no messages when it cannot parse lines and skip them. It's not kind for users to investigate the problems that it cannot parse some lines. 

CsvParserPlugin outputs skipped lines and the line numbers as warning messages when it skips parsing them. We should port the feature to query_string parser.
https://github.com/embulk/embulk/blob/master/embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java#L364

**Comment by uu59** [comment]
Supports at #29, but logging line number is a bit of expensive on current implementation.
If you want that, please reopen this issue.
